### ISSUE TITLE
Miscellaneous code cleanliness tasks

### ISSUE THREAD

**Issue by orecham** [ekxide/rmw_iceoryx2#16]
## Brief Description

Issue for tracking misc. code cleanliness tasks that can either be addressed in a dedicated issue or whilst addressing others.

This issue can remain open indefinitely as a place to add new topics as they are noticed.

## Tasks

1. [ ] Fix name of demo node classes
    1. The nodes working with the `BasicTypes` message is mistakenly named `StringTalker`/`StringListener`
1. [ ] Revise project structure
    1. Implementation details should be moved to a `internal` or `impl` subdirectory to more clearly distinguish between RMW function implementations and the implementation details
1. [ ] Distinct variable convention for RMW types vs. implementation-specific types
    1. e.g. `rmw_node` (rmw type) vs. `node_impl` (implementation-specific)
